config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root 'pages#index'
  get 'pages/show'

  #diary
  get '/home', to: 'children_diaries#home'
  get '/living', to: 'children_diaries#living'
  get '/health', to: 'children_diaries#health'
  get '/visit', to: 'children_diaries#visit'
  get '/information', to: 'children_diaries#information'
  get '/pdf', to: 'post_pdf#index'
  get '/home_pdf', to: 'post_pdf#home'
  
  get '/diary_search', to: 'children_diaries#index'
  
  get 'pdf', to: 'post_pdf#index'
  
  
  resources :children
  resources :children_diaries
  resources :post_pdf, only: :index
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/child.rb
class Child < ApplicationRecord
  has_many :children_diaries,foreign_key: :children_id,dependent: :destroy
  
  validates :name, presence: true, length: { maximum: 50 }
  validates :birthday, presence: true
  validates :child_centers_name, presence: true
  validates :child_number, presence: true
end

app/models/children_diary.rb
class ChildrenDiary < ApplicationRecord
  belongs_to :children, optional: true
  validates :date, presence: true
  
  belongs_to :group
  belongs_to :user
  
  def self.search(search)
    if search != ""
      ChildrenDiary.where(['living LIKE(?) OR health LIKE(?) OR visit LIKE(?) OR information LIKE(?) OR date LIKE(?)',"%#{search}%","%#{search}%","%#{search}%","%#{search}%","%#{search}%"]).order('created_at DESC')
    else
      ChildrenDiary.none
    end
  end
end

app/models/children_diary_log.rb
class ChildrenDiaryLog < ApplicationRecord
  belongs_to :children, optional: true
  validates :date, presence: true
  belongs_to :group
  belongs_to :user
end

app/models/group.rb
class Group < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :lockable, :timeoutable, :trackable, :omniauthable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    before_action :configure_permitted_parameters, if: :devise_controller?
    
    
   def after_sign_in_path_for(resource)
     home_path
   end

   private
  
       def sign_in_required
          redirect_to new_user_session_url unless user_signed_in?
       end
      
      
    protected
        def configure_permitted_parameters
            devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
            devise_parameter_sanitizer.permit(:account_update, keys: [:username])
        end
            
end

app/controllers/baby_controller.rb
class BabyController < ApplicationController
  def living
    @child = Child.find_by(name: "田中　花子") 
    @children_diary = ChildrenDiary.new
  end
  
  def health
    @child = Child.where(group_number: "1")
  end
  
  def visit
    @child = Child.where(group_number: "1")
  end

  def information
    @child = Child.where(group_number: "1")
  end
end

app/controllers/children_controller.rb
class ChildrenController < ApplicationController
  
  def index
    @children = Child.where.not(group_id: "4").order(child_number: "DESC")
  end
  
  def show
    @child = Child.find(params[:id])
  end
 
  def new
    @child = Child.new
  end
  
  def create
    @child = Child.new(child_params)
    @child.group_id = @child.group_number
      if @child.save
        flash[:success] = "#{@child.name} が登録されました"
        render 'children/show'
      else
        render 'children/new'
      end
  end
  
  def edit
     @child = Child.find(params[:id])
  end
  
  def update
    @child = Child.find(params[:id])
    if @child.update(child_params)
      flash[:success] = "児童情報が更新されました"
      redirect_to @child
    else
      render 'edit'
    end
  end
  
  def destroy
    Child.find(params[:id]).destroy
    flash[:success] = "削除されました"
    redirect_to children_path
  end
  
  
  private
  
   def child_params
     params.require(:child).permit(:name,:birthday,:child_centers_name,:child_number,:group_number,:group_id)
   end
  
end

app/controllers/children_diaries_controller.rb
class ChildrenDiariesController < ApplicationController
  
  def show
    @children_diary = ChildrenDiary.find(params[:id])
  end

  def index
    @diaries = ChildrenDiary.search(params[:date])
  end
  
  def destroy
    ChildrenDiary.find(params[:id]).destroy
    flash[:success] = "削除されました"
    redirect_to children_diaries_path, method: :get
  end
  
  def living
    @children = Child.all
    @children_diary = ChildrenDiary.new
  end
  
  def health
    @children = Child.all
    @children_diary = ChildrenDiary.new
  end
  
  def visit
    @children = Child.all
    @children_diary = ChildrenDiary.new
  end
  
  def information
    @children = Child.all
    @children_diary = ChildrenDiary.new
  end
  
  def new
      @children_diary = ChildrenDiary.new
  end
  

  def create
      @children_diary = ChildrenDiary.new(children_diary_params)
      @child = Child.find_by(id: params[:children_diary][:children_id])
      @children_diary.group_id = @child.group_id
      @children_diary.group_number = @child.group_number
      @children_diary_logs = ChildrenDiaryLog.new(living: @children_diary.living, health: @children_diary.health,
                                                    visit: @children_diary.visit, information: @children_diary.information,
                                                    children_id: @children_diary.children_id, group_id: @children_diary.group_id,
                                                    date: @children_diary.date, user: @children_diary.user)

      if @children_diary.save
        flash[:success] = "記録が作成されました"
        @children_diary_logs.save!
        render "children_diaries/show"
          if @children_diary.information.present?
            notifier = Slack::Notifier.new(
              ENV['SLACK_WEBHOOK_URL'],
              channel: "##{ENV['SLACK_CHANNEL']}",
              username: '〇〇施設　共有連絡'
              )
              notifier.ping "新しい連絡事項があります！
                      ```
                       #{@children_diary.information}
                      ```"
            
          end
      else
        flash[:alert] = "日付を選択してください"
        if @children_diary.living.present?
          redirect_to "/living"
        elsif @children_diary.health.present?
          redirect_to "/health"
        elsif @children_diary.visit.present?
          redirect_to "/visit"
        elsif @children_diary.information.present?
          redirect_to "/information"
        end
      end
  end
  
  def edit
     @children_diary = ChildrenDiary.find(params[:id])
  end
  
  def update
    @children_diary = ChildrenDiary.find(params[:id])
    if @children_diary.update(children_diary_params)
      flash[:success] = "内容が追加・更新されました"
        if @children_diary.information.present?
            notifier = Slack::Notifier.new(
              ENV['SLACK_WEBHOOK_URL'],
              channel: "##{ENV['SLACK_CHANNEL']}",
              username: '〇〇施設　共有連絡'
              )
              notifier.ping "更新された連絡事項があります！
                      ```
                       #{@children_diary.information}
                      ```"
        end
      redirect_to @children_diary
    else
      render 'edit'
    end
  end
  
  def search
    @children_diaries = ChildrenDiary.search(params[:diary])
  end
 
  

  
  
  private
  
    def children_diary_params
      params.require(:children_diary).permit(:living,:health,:visit,:information, :children_id, :group_id, :date).merge(user_id: current_user.id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :sign_in_required, only: [:show]
  
  def index
  end

  def show
  end
end

app/controllers/post_pdf_controller.rb
class PostPdfController < ApplicationController
  def home
    @diaries = ChildrenDiary.search(params[:date])
  end
  
  def index
    @diaries = ChildrenDiary.search(params[:search_date]).order(group_number: "DESC")
    @children = Child.all
    respond_to do |format|
      format.pdf do
        post_pdf = PracticePdf::PostPdf.new(@diaries)
        
        send_data post_pdf.render,
          filename: 'post_pdf.pdf',
          type: 'application/pdf',
          disposition: 'inline' # 外すとダウンロード
      end
    end
  end
  
  def contents
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/baby_helper.rb
module BabyHelper
end

app/helpers/boy_helper.rb
module BoyHelper
end

app/helpers/children_diaries_helper.rb
module ChildrenDiariesHelper
end

app/helpers/girl_helper.rb
module GirlHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/baby/home.html.erb
<h1>幼児</h1>


<li>
  <%=link_to '生活状況', "/baby_living"%>
  <%=link_to '健康状況', "/baby_health"%>
  <%=link_to '面会状況', "/baby_visit"%>
  <%=link_to '共有事項', "/baby_information"%>
</li>

app/views/baby/living.html.erb
<!DOCTYPE html>
<html>
<head>
<title>生活状況</title>
</head>
<body>
 <table border="1" width="200">
    <tr>
      <th　width="30%">名前</th>
      <th　width="70%">生活状況</th>
    </tr>
    <tr>
      <td><%= @child.name %> </td>
      <td>
        <%= form_for (@children_diary) do |f| %>
        <%= f.hidden_field :child, :value => @children.id %>
        <%= f.hidden_field :group, :value => group.id %>
        <%= f.hidden_field :user, :value => @user.id %>
        <div class="field">
          <%= f.text_area :living %>
        </div>
        <%= f.submit "保存" %>
        <% end %>
      </td>
    </tr>
     
     
  </table>
</body>
</html>

app/views/boy/home.html.erb
<h1>男子</h1>


<li>
  <%=link_to '生活状況', "/boy_living"%>
  <%=link_to '健康状況', "/boy_health"%>
  <%=link_to '面会状況', "/boy_visit"%>
  <%=link_to '共有事項', "/boy_information"%>
</li>

app/views/children/_btn.html.erb
<div class="container">
  <a class="btn" href="javascript:history.back()">戻る</a>
</div>

app/views/children/_form.html.erb
<div class="c_signup">
      <%= form_with(model: @child,local: true) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        <li>
          <%= f.label :"名前" %>
          <%= f.text_field :name %>
        </li>
        <li>
          <%= f.label :"生年月日" %>
          <%= f.date_select :birthday, use_month_numbers: true,start_year: (Time.now.year - 20),end_year: Time.now.year, default: Date.new(2000, 1, 1) %>
        </li>
        <li>
          <%= f.label :"児童相談所名" %>
          <%= f.text_field :child_centers_name %>
        </li>
        <li>
          <%= f.label :"児童番号" %>
          <%= f.text_field :child_number %>
        </li>
        <li>
          <%= f.label :"所属グループ" %>
          <%= f.select :group_number,[['女子',1],['男子',2],['幼児',3]] %>
        </li>
        <li class="btn">
            <%= f.submit %></li>
      <%end%>
    </div> 

app/views/children/edit.html.erb
<%= render 'btn' %>
<h1 class="page-name">更新</h1>

   <%= render "form" %>

app/views/children/index.html.erb
  <h1 class="page-name">児童一覧</h1>
  <table border="1" width="600">
    <tr>
      <th>名前</th>
      <th>誕生日</th>
      <th>児童相談所名</th>
      <th>児童番号</th>
      <th></th>
      <th></th>
    </tr>
      <% @children.each do |child| %>
    <tr>
      <td><%=child.name%></td>
      <td><%=l child.birthday%></td>
      <td><%=child.child_centers_name%></td>
      <td><%=child.child_number%></td>
      <td><%= link_to "詳細", child,method: :get,class: "index-link"%></td>
      <td><%= link_to "更新", edit_child_path(child.id),class: "index-link"%></td>
        <% if current_user.admin? %>
          <td><%= link_to "削除", child, method: :delete,data: { confirm: "本当に削除しますか?" } ,class: "index-link"%></td>
        <% end %>
    </tr>
      <% end %>
    </tr>
  </table>

app/views/children/new.html.erb
<h1 class="page-name"> 児童　新規登録</h1>

    <%= render "form" %>

app/views/children/show.html.erb
<%= render 'btn' %>

<h1 class="page-name">児童情報</h1>
    <table border="1">
        <thead>
        <tr>
          <th>名前</th>
          <th>生年月日</th>
          <th>児童相談所名</th>
          <th>児童番号</th>
        </tr>
    </thead>
    <tbody>
        <tr>
         <td><%= @child.name %></td>
         <td><%= l @child.birthday %></td>
         <td><%= @child.child_centers_name %></td>
         <td><%= "児童No. #{@child.child_number}" %></td>
        </tr>
    </tbody>
</table>

app/views/children_diaries/edit.html.erb
<%= render 'btn' %>

<h1 class="page-name">追加・更新</h1>
    <h2 class="edit-name">
        <%if @children_diary.living.present?%>
            <%= "生活状況" %>
        <%elsif @children_diary.health.present?%>
            <%= "健康状況" %>
        <%elsif @children_diary.visit.present?%>
            <%= "面会状況" %>
        <%elsif @children_diary.information.present?%>
            <%= "共有事項" %>
        <%end%>
    </h2>
    <tr>
      <td>
        <%= form_with model: @children_diary do |f| %>
          <div class="form-field">
            <li>
                <%if @children_diary.living.present?%>
                    <%= f.text_area :living %>
                <%elsif @children_diary.health.present?%>
                    <%= f.text_area :health %>
                <%elsif @children_diary.visit.present?%>
                    <%= f.text_area :visit %>
                <%elsif @children_diary.information.present?%>
                    <%= f.text_area :information %>
                <%end%>
            </li>
            <li class="btn"><%= f.submit "更新" %></li>
        <% end %>
          </div>
      </td>
    </tr>

app/views/children_diaries/health.html.erb
<%= render 'btn' %>
<h1 class="page-name">健康状況</h1>
<tr>
  <td>
        <%= form_with model: @children_diary, :local => true do |f| %>
          <div class="form-field">
            <li><%= f.collection_select(:children_id, @children, :id, :name)%></li>
            <li><%= f.date_field :date %></li>
            <li><%= f.text_area :health %></li>
            <li class="btn"><%= f.submit "保存" %></li>          
          </div>
        <% end %>
      </td>
</tr>

app/views/children_diaries/home.html.erb
   <h1 class="page-name">〇〇施設　養護日誌</h1>
   
   <div class="home">
    <div class="home_field">
     <div class="home_field_link">
      <p><%= link_to '生活状況', "/living" ,class: "link"%></p>
      <p><%= image_tag 'children.jpg' ,width: '50%', height: '30%' %></p>
     </div>
    </div>
     
    <div class="home_field">
     <div class="home_field_link">
      <p><%= link_to '健康状況', "/health" ,class: "link"%></p>
      <p><%= image_tag 'health.jpg',width: '50%', height: '30%'  %></p>
     </div>
    </div>
    
    <div class="home_field">
     <div class="home_field_link">
      <p><%= link_to '面会状況', "/visit" ,class: "link"%></p>
      <p><%= image_tag 'flower.jpg',width: '50%', height: '30%'  %></p>
     </div>
    </div>
     
    <div class="home_field">
     <div class="home_field_link">
      <p><%= link_to '共有事項', "/information",class: "link" %></p>
      <p><%= image_tag 'information.jpg',width: '50%', height: '30%'  %></p>
     </div>
    </div>
   </div>
 

app/views/children_diaries/index.html.erb
<h1 class="page-name">児童状況一覧</h1>

  <div class="search">
    <%= form_with url: diary_search_path, method: :get, local: true do |f| %>
  　   <%= f.date_field :date %>
    　<%= f.submit "検索" %>
    <% end %>
  </div>
  
  <table border="1">
  <% unless @diaries.present? %>
    <h2 class = "seach-result">検索結果はありません</h2>
  <% else %>
  <thead>
    <tr>
      <th>児童名</th>
      <th class="table-diary">日誌内容</th>
      <th>年月日</th>
      <th> </th>
      <th> </th>
      <th> </th>
    </tr>
  </thead>
  <tbody>
    <% @diaries.each do |diary| %>
      <% child = Child.find_by(id: diary.children_id) %>
      <tr>
        <td><% if diary.information.present? %>
            <%= " " %>
            <% else %>
            <%= child.name %><%end%></td>
        <td>
             <%if diary.living.present?%><%= "(生活状況)   #{diary.living}"%><%end%>
             <%if diary.health.present?%><%= "(健康状況)   #{diary.health}"%><%end%>
             <%if diary.visit.present?%><%= "(面会状況)   #{diary.visit}"%><%end%>
             <%if diary.information.present?%><%= "(共有事項)   #{diary.information}"%><%end%>
        </td>
        <td><%= l(diary.date,format: :short) %></td>
        <div class="link">
          <td><%= link_to "詳細を見る",diary,method: :get,class: "index-link" %></td>
          <td><%= link_to "削除",diary, method: :delete,class: "index-link" %></td>
          <td><%= link_to "追加・更新", edit_children_diary_path(diary.id),class: "index-link" %></td>
        </div>
      </tr>
    <% end %>
  </tbody>
  <% end %>
</table>

<div class="pdf">
  <div class="btn-pdf">
    <%= link_to "日誌印刷",  post_pdf_index_url(format: "pdf",:children_diary => @diaries, :search_date => params[:date]),class: "link" %>
  </div>
</div>

app/views/children_diaries/information.html.erb
<%= render 'btn' %>

<h1 class="page-name">共有事項</h1>
  <tr>
    <td>
        <%= form_with model: @children_diary, :local => true do |f| %>
          <div class="form-field">
            <li><%= f.collection_select(:children_id, @children, :id, :name)%></li>
            <li><%= f.date_field :date %></li>
            <li><%= f.text_area :information %></li>
            <li class="btn"><%= f.submit "保存" %></li>
          </div>
        <% end %>
      </td>
  </tr>

app/views/children_diaries/living.html.erb
<h1>生活 状況</h1>
    <tr>
      <td>
        <%= form_with model: @children_diary, :local => true do |f| %>
          <div class="field">
            <%= f.collection_select(:children_id, @children, :id, :name)%>
            <%= f.date_field :date %>
            <%= f.text_area :living %>
          </div>
          <%= f.submit "保存" %>
        <% end %>
      </td>
    </tr>  

app/views/children_diaries/search.html.erb
<div class="search">
 <%= form_with url: search_path, method: :get, local: true do |f| %>
  <%= f.text_field :diary %>
  <%= f.submit "検索" %>
 <% end %>
</div>


<table border="1" width="1000">
  <% unless @children_diaries.present? %>
    <h2 class = "seach-result">検索結果はありません</h2>
  <% else %>
  <thead>
    <tr>
      <th>児童名</th>
      <th>生活状況</th>
      <th>健康状況</th>
      <th>面会状況</th>
      <th>共有事項</th>
      <th>年月日</th>
    </tr>
  </thead>
  <tbody>
    <% @children_diaries.each do |children_diary| %>
      <% child = Child.find_by(id: children_diary.children_id) %>
      <tr>
        <td><%= child.name %></td>
        <td><%= children_diary.living %></td>
        <td><%= children_diary.health %></td>
        <td><%= children_diary.visit %></td>
        <td><%= children_diary.information %></td>
        <td><%= children_diary.date %></td>
        <td><%= link_to "詳細を見る",children_diary,method: :get %></td>
        <td><%= link_to "削除",children_diary, method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
  <% end %>
</table>

app/views/children_diaries/show.html.erb
<%= render 'btn' %>

<h1 class="page-name">日誌詳細</h1>
    <table border="1">
        <% @child = Child.find_by(id: @children_diary.children_id) %>
        <% @user = User.find_by(id: @children_diary.user_id)%>
        <thead>
        <tr>
          <th>児童名</th>
          <th>日付</th>
          <th class="table-diary">日誌内容</th>
          <th>入力者名</th>
        </tr>
    </thead>
    <tbody>
        <tr>
         <td><%= @child.name%></td>
         <td><%= l @children_diary.date%></td>
         <td>
             <%if @children_diary.living.present?%><%= "(生活状況)   #{@children_diary.living}"%><%end%>
             <%if @children_diary.health.present?%><%= "(健康状況)   #{@children_diary.health}"%><%end%>
             <%if @children_diary.visit.present?%><%= "(面会状況)   #{@children_diary.visit}"%><%end%>
             <%if @children_diary.information.present?%><%= "(共有事項)   #{@children_diary.information}"%><%end%>
         </td>
         <td><%= @user.username%></td>
        </tr>
    </tbody>
</table>
    

app/views/children_diaries/visit.html.erb
<%= render 'btn' %>

<h1 class="page-name">面会状況</h1>
  <tr>
    <td>
        <%= form_with model: @children_diary, :local => true do |f| %>
          <div class="form-field">
            <li><%= f.collection_select(:children_id, @children, :id, :name)%></li>
            <li><%= f.date_field :date %></li>
            <li><%= f.text_area :visit %></li>
            <li class="btn"><%= f.submit "保存" %></li>
          </div>
        <% end %>
      </td>
    </td>
  </tr>

app/views/girl/home.html.erb
<h1>女子</h1>


<li>
  <%=link_to '生活状況', "/girl_living"%>
  <%=link_to '健康状況', "/girl_health"%>
  <%=link_to '面会状況', "/girl_visit"%>
  <%=link_to '共有事項', "/girl_information"%>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>DiaryApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!--flash.each do |message_type, message|-->
      <!--message -->
     <!--end -->
    <header>
      <nav>
          <% if user_signed_in? %>
          <div class="headder-link">
            <strong><%= link_to current_user.username,edit_user_registration_path,class: "headder-link" %></strong>
              <%= link_to '児童一覧', children_path,class: "headder-link" %>
              <%= link_to '児童状況', "/home",class: "headder-link"%>
              <%= link_to '児童状況一覧', children_diaries_path, method: :get,class: "headder-link"  %>
                <% if current_user.admin? %>
                  <%= link_to '児童登録', new_child_path,class: "headder-link" %>
                <% end %>
          <% else %>
              <%= link_to '新規登録', new_user_registration_path,class: "headder-link" %>
              <%= link_to 'ログイン', new_user_session_path,class: "headder-link" %>
          <% end %>
          </div>
      </nav>
    </header>
    <main>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    
    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </main>
    <footer>
      <ul class="footer">
        <p> 社会福祉法人　〇〇園</p>
          <% if user_signed_in? %>
            <%= link_to 'プロフィール変更', edit_user_registration_path,class: "footer-link" %>
            <%= link_to 'ログアウト', destroy_user_session_path, method: :delete ,class: "footer-link"%>
          <%end%>
      </ul>
    </footer>
  </body>
</html>

app/views/pages/index.html.erb
    <ul class="welcome-user">
      <h1>〇〇学園　児童養護日誌</h1>
    </ul>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
       入力内容に誤りが <%= pluralize(object.errors.count, "つ　あります") %>.
    </div>
    <ul>
    <% @child.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>